import { Footer } from "@/components/blocks/footer";
import { Header } from "@/components/blocks/header";
import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-full flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <Header />
        <TooltipProvider>
          <main className="flex justify-center items-center min-h-[calc(100vh-7rem)] w-full h-full p-2">
            {children}
          </main>
        </TooltipProvider>
        <Footer />
      </body>
    </html>
  );
}
